"""Add is_internal_only to Task

Revision ID: 5c6766ddd2a2
Revises: fce8be956103
Create Date: 2026-01-14 11:59:02.513094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6766ddd2a2'
down_revision = 'fce8be956103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal_only', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_is_internal_only'), ['is_internal_only'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_is_internal_only'))
        batch_op.drop_column('is_internal_only')

    # ### end Alembic commands ###
