"""Add task attachments table

Revision ID: e4f706ecd984
Revises: merge_99f0a8a1a2
Create Date: 2025-12-24 11:09:33.206399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f706ecd984'
down_revision = 'merge_99f0a8a1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('alert_logs_task_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('alert_logs_task_id_fkey'), 'tasks', ['task_id'], ['id'])

    op.drop_table('task_attachments')
    # ### end Alembic commands ###
